#![feature(error_in_core)]

[package]
name = "hydra-ogmios"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0"
ciborium = "0.2.2"
hex = "0.4.3"
pallas-primitives = "0.30.2"
minicbor = "0.25.1"
